MDScreen:
    name: "splash"

    AsyncImage:
        source: '8cAbkxGKi.gif'
        pos: 0, 0
        allow_stretch: True
        keep_ratio:False

    Image:
        source: "logo.png"
        size_hint: 0.9, 0.9
        pos_hint: {'center_x': 0.5,'center_y': 0.6}

    AsyncImage:
        source: 'z5EsuzqT_V1.gif'
        pos: 0, 0
        allow_stretch: True
        keep_ratio:False
        pos_hint: {'center_x': 0.5, 'center_y': 0.3}
        size_hint: (0.3, 0.3)